newpolls/newapp/urls.py
#!/usr/bin/env python 
# -*- coding:utf-8 -*-

from django.urls import  path

from . import views

app_name = 'newpolls'
urlpatterns = [
    #  ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

newpolls/newpolls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('newapp/',include('newapp.urls')),
    path('admin/', admin.site.urls),
]

newpolls/newapp/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.ImageField(default=0)

    def __str__(self):
        return self.choice_text

newpolls/newapp/views.py
from django.shortcuts import render
from django.http import  HttpResponseRedirect
from django.template import loader
from .models import Question, Choice
from django.shortcuts import get_object_or_404
# Create your views here.

def index(request):
    # 使用render()函数
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('newapp/index.html')
    context = {'latest_question_list': latest_question_list}
    return render(request, "newapp/index.html", context)


    # 使用template模板技术
    # latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('newapp/index.html')
    # context = {
    #     'latest_question_list': latest_question_list
    # }
    # return HttpResponse(template.render(context, request))

    # output = ', '.join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)
    # return HttpResponse("娇娇酱，我亲爱的宝贝！！！")


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'newapp/detail.html', {'question': question})

    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist111")
    # return render(request, 'newpolls/detail.html', {'question': question})
    # response = "You're looking at the results of question %s."
    # return HttpResponse(response % question_id)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})
    # response = "You're looking at the results of question %s."
    # return HttpResponse(response % question_id)


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "newpolls/detail.html", {
            "question": question,
            "error_message": "You didni't select a choice.",
        })
    else:
        selected_choice.vote += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("newapp: results", args=(question.id,)))

newpolls/newapp/templates/newapp/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <!--{% if error_message %}<p><strong>{{ error_message }}</strong></p>{{% endif %}}-->

    <!--<form action="{% url 'newpolls:vote' question.id %}" method="post">-->
        <!--{% csrf_token %}-->
        <!--{% for choice in question.choice_set.all %}-->
            <!--<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>-->
            <!--<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>-->
        <!--{% endfor %}-->
        <!--<input type="submit" value="vote"/>-->
    <!--</form>-->
    <ul>
        {{ for choice in question.choice_set.all }}
        <li>{{ choice.choice_text }}</li>
        {{ endfor }}
    </ul>
</body>
</html>

newpolls/newapp/templates/newapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>http://www.娇宝贝.com</title>
</head>
<body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <!--<li><a herf = "/newapp/{{ question_list }}/">{{ question.question_text }}</a></li>-->
        <li><a herf = "{% url 'newpolls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No newapp are availables.</p>
    {% endif %}
</body>
</html>

newpolls/newapp/templates/newapp/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.vote}} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>